name: Lambda Deployer
description: Deploy Lambda Code
author: https://github.com/envato
requirements: []
configuration:
  properties:
    function_name:
      type: string
    zip_file:
      type: string
    path:
      type: string
    s3_bucket:
      type: string
    s3_key:
      type: string
    region:
      type: string
  required:
    - function_name
    - zip_file
  additionalProperties: false
